### ISSUE TITLE
Initial Questions & Problems

### ISSUE THREAD

**Issue by jrobmey** [robinmdm/assignment-2a#2]
**General problems:**

1. If we aren't mistaken the assignment requires us to develop your webpage in your repository. However you already started to develop your clients webpage in this repo.
2. Please activate github-pages.

**Questions regarding content and functionality:**

- contact.html: Who is the CEO and where is the image? Also, where should it be placed on the page?
- login.html: Its not possible to implement this functionality in github-pages. Also Assignment 2a states: "your website should not include interactive elements".
- course.html: Where are the images?
- country.html: Where are the images?
- field.html: Where are the images?
- jobs.html: The page exists only in the wireframe and not in the webpages list.
- emailcontact.html: The page exists only in the webpages list, but not in the wireframe.
- eligibility.html: What should the questions (scale 1-10) look like? How should the algorithm work, that determines the eligibility?
- university.xml and contact us xml.txt: Where should this be placed on the website and how should it be presented? This is not clear from the wireframe.

**Comment by robinmdm** [comment]
Thank you for pointing out the issues. We will work on that and get back to you quickly. In the meantime, if you have any more questions or inquiries please let us know.

Thanks.

**Comment by robinmdm** [comment]
1. We will talk to the teacher and then will know for sure, what to do with this.
2. Yes, we will.


Answers to your Questions regarding content and functionality:

-  contact.html: Who is the CEO and where is the image? Also, where should it be placed on the page?

-->> There is no CEO, there will be only office images. You can find it on the image folder --> office folder --> office images. 

- login.html: Its not possible to implement this functionality in github-pages. Also Assignment 2a states: "your website should not include interactive elements".

-->> You do not have to make any interactive element. Just create forms and that will be all. Just a mockup will be enough. For simplification, create 2 hyperlinks 1 for Guardian and 1 for student that will be all.

- course.html: Where are the images?  country.html: Where are the images? field.html: Where are the images?

-->> In all these, there will be an image of door. In the image folder, you will find an imaged named "door". That image will be used for all these courses, countries, fields. Under the door there will be title. You can see from the wireframe.

- jobs.html: The page exists only in the wireframe and not in the webpages list.

-->> We will update the wireframe. You do not need to develop this page.

- emailcontact.html: The page exists only in the webpages list, but not in the wireframe.

-->> We will update the webpages list. You do not have to develop it. Contact page will be enough

- eligibility.html: What should the questions (scale 1-10) look like? How should the algorithm work, that determines the eligibility?

-->> We thought we have to add something related to javascript, which is why we created this page. But as we do not have to do anything with javascript, you do not have to develop this page also. We will update our list and wireframe thereby.

- university.xml and contact us xml.txt: Where should this be placed on the website and how should it be presented? This is not clear from the wireframe.

-->> This is not something that has to be shown on the website. This holds some information, such as, you can see there which courses will be available for bachelor, and masters, also which fields are available.

**Comment by robinmdm** [comment]
We will update our wireframe and diagram so that you can have the updated version.

**Comment by chrir0** [comment]
I will update the diagrams ASAP after my course at around 3 PM and clarify any other problems if there is still any by then

**Comment by chrir0** [comment]
1. Question: university.xml and contact us xml.txt: Where should this be placed on the website and how should it be presented? This is not clear from the wireframe.
Reply: We were not 100% sure in what way this xml files should be used. We created both of these to "extract" the information to later show them in the corresponding pages, in this case contacts and after a client selected their continent country field etc. to go through the XML to find universities fitting of the selection. But as javascript won't be used, this information does not really have to be included anymore. If you want you can put an element with some kind of scrollbar that shows all available courses from the XML for the currently selected university (in this project we just expect a single university to be "functional" on the websites which is the BTU provided in the XML file).

2. Question: eligibility.html: What should the questions (scale 1-10) look like? How should the algorithm work, that determines the eligibility?
Reply: If you want you can still implement this it's up to you considering javascript code is not expected. However the idea was to just take the value 0 - 10 or yes / no as 0 or 10 value, then add everything together and get the average. if it's 0-3 low 4 - 7 medium 8-10 high with a corresponding message of "high / medium or /low eligibility".

3. The wireframe was wrongfully updated by me and should be more clear now (one page was missing and I uploaded the wrong format prior). Keep in mind that the "e-mail" questions page was already made before knowing these kind of UI components should not be used, thus feel free to ignore that page entirely too.

4. Github Pages will be setup soon.

**Comment by chrir0** [comment]
Do you still have any questions at this given moment? Else I will close this issue for now

**Comment by jrobmey** [comment]
We have no further questions for now.
