### ISSUE TITLE
Redirect for guardian

### ISSUE THREAD

**Issue by noerenil** [robinmdm/assignment-2a#4]
In your website design diagram you list "List of questions and reply field" as a redirect for when a guardian signs in. You added this page in the wireframe but we can't find it in the webpages list.

The problem is that there is no text to add, your wireframe only shows placeholders and we couldn't find any other source. If we should implement this page, we will need some text to fill it. Or did we just miss it in the repository?

And regarding the other redirect (upload document and select field of experience) we also can't find any information on it, not even in the wireframe. Is this page relevant?

**Comment by robinmdm** [comment]
In your website design diagram you list "List of questions and reply field" as a redirect for when a guardian signs in. You added this page in the wireframe but we can't find it in the webpages list.

The problem is that there is no text to add, your wireframe only shows placeholders and we couldn't find any other source. If we should implement this page, we will need some text to fill it. Or did we just miss it in the repository?

-->> You can leave this, you do not need to build this page. We are working on the updated version of the wireframe, soon we will publish it.

And regarding the other redirect (upload document and select field of experience) we also can't find any information on it, not even in the wireframe. Is this page relevant?

-->> Nope, this page is not relevant. At first, we thought there would be something related to Javascript. Since it's not the case, we changed our plan, but we did not update the wireframe, that is what happened.

Hope that helps. Feel free to ask again for any issues. Happy Coding!!

**Comment by noerenil** [comment]
Thank you, in that case we won't implement these pages.
